CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
        ID SERIAL,
        NAME CHARACTER VARYING(255) COLLATE PG_CATALOG."default" NOT NULL,
        EMAIL CHARACTER VARYING(255) COLLATE PG_CATALOG."default" NOT NULL,
        EMAIL_VERIFIED_AT TIMESTAMP WITHOUT TIME ZONE,
        USERNAME TEXT COLLATE PG_CATALOG."default" NOT NULL,
        PASSWORD CHARACTER VARYING(255) COLLATE PG_CATALOG."default" NOT NULL,
        REMEMBER_TOKEN CHARACTER VARYING(100) COLLATE PG_CATALOG."default" DEFAULT NULL::CHARACTER VARYING,
        CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
        UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        CONSTRAINT USERS_PKEY PRIMARY KEY (ID)
);
INSERT INTO
        USERS (NAME, EMAIL, USERNAME, PASSWORD) VALUES (
                'Administrador',
                'admin@loti.com',
                'admin',
                '$2y$10$jsPuTA62MG6/p/xC2J8I/OLJVCWd4nJsWzpItHNXse8NzG9rQqrx6'
        ) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.residenciales
(
    id serial,
    nombre text NOT NULL,
    descripcion text NOT NULL,
    id_user bigint NOT NULL,
        imagen text,
    created_at timestamp(0) without time zone DEFAULT now(),
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT residenciales_pkey PRIMARY KEY (id)
);
ALTER TABLE residenciales ADD CONSTRAINT residenciales_id_user_foreign FOREIGN KEY (id_user) REFERENCES users (id);

CREATE TABLE IF NOT EXISTS public.bloques
(
    id serial,
    nombre text NOT NULL,
    created_at timestamp(0) without time zone DEFAULT now(),
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT bloques_pkey PRIMARY KEY (id)
);

INSERT INTO bloques (nombre) VALUES
('A'),('B'),('C'),('D'),('E'),('F'),('G'),
('H'),('I'),('J'),('K'),('L'),('M'),('N'),
('O'),('P'),('Q'),('R'),('S'),('T'),('U'),
('V'),('W'),('X'),('Y'),('Z') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.bloques_residenciales
(
    id serial,
    id_bloque bigint NOT NULL,
    id_residencial bigint NOT NULL,
    created_at timestamp(0) without time zone DEFAULT now(),
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT bloques_residenciales_pkey PRIMARY KEY (id)
);
ALTER TABLE bloques_residenciales ADD CONSTRAINT bloques_residenciales_id_bloque_foreign FOREIGN KEY (id_bloque) REFERENCES bloques (id);
ALTER TABLE bloques_residenciales ADD CONSTRAINT bloques_residenciales_id_residencial_foreign FOREIGN KEY (id_residencial) REFERENCES residenciales (id);      

CREATE TABLE IF NOT EXISTS PUBLIC.ESTADOS_CATALOGO (
        ID SERIAL,
        NOMBRE TEXT NOT NULL,
        DESCRIPCION TEXT,
        CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
        UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        CONSTRAINT ESTADOS_PKEY PRIMARY KEY (ID)
);

INSERT INTO estados_catalogo (nombre, descripcion) VALUES
('Disponible', 'Estado que indica que el lote está disponible para la venta'),
('Reservado', 'Estado que indica que el lote ha sido apartado temporalmente'),
('Vendido', 'Estado que indica que el lote ya ha sido vendido') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS PUBLIC.CLIENTES (
        ID SERIAL,
        PRIMER_NOMBRE TEXT NOT NULL,
        SEGUNDO_NOMBRE TEXT,
        PRIMER_APELLIDO TEXT NOT NULL,
        SEGUNDO_APELLIDO TEXT,
        IDENTIDAD TEXT NOT NULL,
        CONTACTO_TELEFONICO TEXT NOT NULL,
        CONTACTO_TELEFONICO_2 TEXT,
        CORREO_ELECTRONICO TEXT,
        DIRECCION TEXT NOT NULL,
        IMAGEN TEXT,
        ID_USER BIGINT NOT NULL,
        CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
        UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        CONSTRAINT CLIENTES_PKEY PRIMARY KEY (ID)
);

ALTER TABLE CLIENTES
ADD CONSTRAINT CLIENTES_ID_USER_FOREIGN FOREIGN KEY (ID_USER) REFERENCES USERS (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.REFERENCIAS (
        ID SERIAL,
        NOMBRE_COMPLETO TEXT NOT NULL,
        CONTACTO_TELEFONICO TEXT NOT NULL,
        DIRECCION TEXT NOT NULL,
        IMAGEN TEXT,
        ID_CLIENTE BIGINT NOT NULL,
        CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
        UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        CONSTRAINT REFERENCIAS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE REFERENCIAS
ADD CONSTRAINT REFERENCIAS_ID_CLIENTE_FOREIGN FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.BENEFICIARIOS (
        ID SERIAL,
        NOMBRE_COMPLETO TEXT NOT NULL,
        IDENTIDAD TEXT NOT NULL,
        PARENTEZCO TEXT NOT NULL,
        CONTACTO_TELEFONICO TEXT NOT NULL,
        CONTACTO_TELEFONICO_2 TEXT,
        CORREO_ELECTRONICO TEXT,
        DIRECCION TEXT NOT NULL,
        ID_CLIENTE BIGINT NOT NULL,
        CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
        UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        CONSTRAINT BENEFICIARIOS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE BENEFICIARIOS
ADD CONSTRAINT BENEFICIARIOS_ID_CLIENTE_FOREIGN FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.LOTES (
        ID SERIAL,
        NOMBRE TEXT NOT NULL,
        LOTE INTEGER NOT NULL,
        AREA NUMERIC NOT NULL,
        NORTE NUMERIC NOT NULL,
        SUR NUMERIC NOT NULL,
        ESTE NUMERIC NOT NULL,
        OESTE NUMERIC NOT NULL,
        PRECIO NUMERIC NOT NULL,
        ANIOS_FINANCIAMIENTO NUMERIC NOT NULL,
        ID_CLIENTE_RESERVAR BIGINT,
        RESERVADO_HASTA TIMESTAMP(0) WITHOUT TIME ZONE,
        ID_BLOQUE_RESIDENCIAL BIGINT NOT NULL,
        CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
        UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
        CONSTRAINT LOTES_PKEY PRIMARY KEY (ID)
);

ALTER TABLE LOTES
ADD CONSTRAINT LOTES_ID_CLIENTE_RESERVAR_FOREIGN FOREIGN KEY (ID_CLIENTE_RESERVAR) REFERENCES CLIENTES (ID);

ALTER TABLE LOTES
ADD CONSTRAINT LOTES_ID_BLOQUE_RESIDENCIAL_FOREIGN FOREIGN KEY (ID_BLOQUE_RESIDENCIAL) REFERENCES BLOQUES_RESIDENCIALES (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.CATALOGO_TIPO_PAGO (
    ID SERIAL,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT,
    CONSTRAINT CATALOGO_TIPO_PAGO_PKEY PRIMARY KEY (ID)
);

INSERT INTO CATALOGO_TIPO_PAGO (NOMBRE, DESCRIPCION) VALUES ('Contado', 'Pago único de contado'), ('Financiado', 'Pago financiado en cuotas');

CREATE TABLE IF NOT EXISTS PUBLIC.CATALOGO_ESTADO_VENTA (
    ID SERIAL,
    NOMBRE TEXT NOT NULL,
    DESCRIPCION TEXT,
    CONSTRAINT CATALOGO_ESTADO_VENTA_PKEY PRIMARY KEY (ID)
);

INSERT INTO CATALOGO_ESTADO_VENTA (NOMBRE, DESCRIPCION) VALUES ('Activo', 'Venta activa con pagos pendientes'), ('Pagado', 'Venta totalmente pagada'), ('Cancelado', 'Venta cancelada');

CREATE TABLE IF NOT EXISTS PUBLIC.VENTAS (
    ID SERIAL,
    ID_CLIENTE BIGINT NOT NULL,
    TIPO_PAGO INTEGER NOT NULL REFERENCES CATALOGO_TIPO_PAGO(ID),
    ESTADO INTEGER NOT NULL REFERENCES CATALOGO_ESTADO_VENTA(ID),
    TOTAL_CONTADO NUMERIC NOT NULL,
    ANIOS_FINANCIAMIENTO INTEGER NOT NULL,
    TASA_INTERES NUMERIC NOT NULL,
    PRIMA NUMERIC NOT NULL,
    CUOTAS INTEGER NOT NULL,
    TOTAL_INTERESES NUMERIC NOT NULL,
    TOTAL_PAGAR NUMERIC NOT NULL,
    CUOTA_MENSUAL NUMERIC NOT NULL,
    DIA_COBRO_MES INTEGER NOT NULL,
    FECHA_VENTA TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
    CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT VENTAS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE VENTAS
ADD CONSTRAINT VENTAS_ID_CLIENTE_FOREIGN FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.LOTES_VENDIDOS (
    ID SERIAL,
    ID_LOTE BIGINT NOT NULL,
    ID_VENTA BIGINT NOT NULL,
    CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT LOTES_VENDIDOS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE LOTES_VENDIDOS
ADD CONSTRAINT LOTES_VENDIDOS_ID_LOTE_FOREIGN FOREIGN KEY (ID_LOTE) REFERENCES LOTES (ID);

ALTER TABLE LOTES_VENDIDOS
ADD CONSTRAINT LOTES_VENDIDOS_ID_VENTA_FOREIGN FOREIGN KEY (ID_VENTA) REFERENCES VENTAS (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FECHAS_COBROS (
    ID SERIAL,
    ID_VENTA BIGINT NOT NULL,
    FECHA_COBRO DATE NOT NULL,
    FECHA_PAGO TIMESTAMP(0) WITHOUT TIME ZONE,
    CANTIDAD_PAGO NUMERIC,
    CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT FECHAS_COBROS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE FECHAS_COBROS
ADD CONSTRAINT FECHAS_COBROS_ID_VENTA_FOREIGN FOREIGN KEY (ID_VENTA) REFERENCES VENTAS (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.LOTES_APARTADOS (
    ID SERIAL,
    ID_LOTE BIGINT NOT NULL,
    ID_USER BIGINT NOT NULL,
    CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
    CONSTRAINT LOTES_APARTADOS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE LOTES_APARTADOS
ADD CONSTRAINT LOTES_APARTADOS_ID_LOTE_FOREIGN FOREIGN KEY (ID_LOTE) REFERENCES LOTES (ID);

ALTER TABLE LOTES_APARTADOS
ADD CONSTRAINT LOTES_APARTADOS_ID_USER_FOREIGN FOREIGN KEY (ID_USER) REFERENCES USERS (ID);
