
CREATE TABLE IF NOT EXISTS public.residenciales
(
    id serial,
    nombre text NOT NULL,
    descripcion text NOT NULL,
    id_user bigint NOT NULL,
	imagen text,
    created_at timestamp(0) without time zone DEFAULT now(),
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT residenciales_pkey PRIMARY KEY (id)
);
ALTER TABLE residenciales ADD CONSTRAINT residenciales_id_user_foreign FOREIGN KEY (id_user) REFERENCES users (id);

CREATE TABLE IF NOT EXISTS public.bloques
(
    id serial,
    nombre text NOT NULL,
    created_at timestamp(0) without time zone DEFAULT now(),
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT bloques_pkey PRIMARY KEY (id)
);

INSERT INTO bloques (nombre) VALUES
('A'),('B'),('C'),('D'),('E'),('F'),('G'),
('H'),('I'),('J'),('K'),('L'),('M'),('N'),
('O'),('P'),('Q'),('R'),('S'),('T'),('U'),
('V'),('W'),('X'),('Y'),('Z');

CREATE TABLE IF NOT EXISTS public.bloques_residenciales
(
    id serial,
    id_bloque bigint NOT NULL,
    id_residencial bigint NOT NULL,
    created_at timestamp(0) without time zone DEFAULT now(),
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT bloques_residenciales_pkey PRIMARY KEY (id)
);
ALTER TABLE bloques_residenciales ADD CONSTRAINT bloques_residenciales_id_bloque_foreign FOREIGN KEY (id_bloque) REFERENCES bloques (id);
ALTER TABLE bloques_residenciales ADD CONSTRAINT bloques_residenciales_id_residencial_foreign FOREIGN KEY (id_residencial) REFERENCES residenciales (id);

CREATE TABLE PUBLIC.ESTADOS_CATALOGO (
	ID SERIAL,
	NOMBRE TEXT NOT NULL,
	DESCRIPCION TEXT,
	CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
	UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	CONSTRAINT ESTADOS_PKEY PRIMARY KEY (ID)
);

INSERT INTO estados_catalogo (nombre, descripcion) VALUES
('Disponible', 'Estado que indica que el lote está disponible para la venta'),
('Reservado', 'Estado que indica que el lote ha sido apartado temporalmente'),
('Vendido', 'Estado que indica que el lote ya ha sido vendido');

CREATE TABLE PUBLIC.CLIENTES (
	ID SERIAL,
	PRIMER_NOMBRE TEXT NOT NULL,
	SEGUNDO_NOMBRE TEXT,
	PRIMER_APELLIDO TEXT NOT NULL,
	SEGUNDO_APELLIDO TEXT,
	IDENTIDAD TEXT NOT NULL,
	CONTACTO_TELEFONICO TEXT NOT NULL,
	CONTACTO_TELEFONICO_2 TEXT,
	CORREO_ELECTRONICO TEXT,
	DIRECCION TEXT NOT NULL,
	IMAGEN TEXT,
	ID_USER BIGINT NOT NULL,
	CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
	UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	CONSTRAINT CLIENTES_PKEY PRIMARY KEY (ID)
);

ALTER TABLE CLIENTES
ADD CONSTRAINT CLIENTES_ID_USER_FOREIGN FOREIGN KEY (ID_USER) REFERENCES USERS (ID);

CREATE TABLE PUBLIC.REFERENCIAS (
	ID SERIAL,
	NOMBRE_COMPLETO TEXT NOT NULL,
	CONTACTO_TELEFONICO TEXT NOT NULL,
	DIRECCION TEXT NOT NULL,
	IMAGEN TEXT,
	ID_CLIENTE BIGINT NOT NULL,
	CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
	UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	CONSTRAINT REFERENCIAS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE REFERENCIAS
ADD CONSTRAINT REFERENCIAS_ID_CLIENTE_FOREIGN FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);

CREATE TABLE IF NOT EXISTS PUBLIC.LOTES (
	ID SERIAL,
	NOMBRE TEXT NOT NULL,
	AREA NUMERIC NOT NULL,
	NORTE NUMERIC NOT NULL,
	SUR NUMERIC NOT NULL,
	ESTE NUMERIC NOT NULL,
	OESTE NUMERIC NOT NULL,
	PRECIO NUMERIC NOT NULL,
	ANIOS_FINANCIAMIENTO NUMERIC NOT NULL,
	ID_CLIENTE_RESERVAR BIGINT,
	RESERVADO_HASTA TIMESTAMP(0) WITHOUT TIME ZONE,
	ID_BLOQUE_RESIDENCIAL BIGINT NOT NULL,
	CREATED_AT TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NOW(),
	UPDATED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	DELETED_AT TIMESTAMP(0) WITHOUT TIME ZONE,
	CONSTRAINT LOTES_PKEY PRIMARY KEY (ID)
);

ALTER TABLE LOTES
ADD CONSTRAINT LOTES_ID_CLIENTE_RESERVAR_FOREIGN FOREIGN KEY (ID_CLIENTE_RESERVAR) REFERENCES CLIENTES (ID);

ALTER TABLE LOTES
ADD CONSTRAINT LOTES_ID_BLOQUE_RESIDENCIAL_FOREIGN FOREIGN KEY (ID_BLOQUE_RESIDENCIAL) REFERENCES BLOQUES_RESIDENCIALES (ID);